<?php
session_start();
if (!$_SESSION['user']) {
    header('Location: index.php');
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="css/registered_styles.css">
</head>

<body>

    <?php require_once 'layout/registered_header.php' ?>

    <article>
        <!-- <?php
        print_r($_SESSION['user']);
        ?>
        <br> -->
        <?php
        if (isset($_SESSION['user']['level'])) {
            $user_level = $_SESSION['user']['level'];

            if ($user_level == 'A1') {
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/xhDLXFJNwBY?si=xjG4aBzBaFqceP42" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/gMHxEO3LrQg?si=-uXTFP_NDoMGemF_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/6fmSFanrHN4?si=U512k4JeGNe825uq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/PWxci3bYpek?si=IhTjGsfHida8CMXM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/szK6cb-xiu4?si=igP31HvSq-hPft8b" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/rglxaZ2-4i4?si=3PBiT3Q-LlC3gWrj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/gAHiiica4cQ?si=zSdmAP31vku8K9pL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/wND26Pwl-rw?si=eBmMuxCUzJfowQfi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/-qj_nSr7X2I?si=EtHtQ-cnfXHfrX13" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/jgxDGr81-_U?si=LpjQHdpdtkeHWXLR" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/2upHgXUo4pA?si=-JkuuhmlMArrvhq1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/-onOu3yvQlk?si=Uass9jqcBo9yH1FX" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/FNcPdtk3jo4?si=F5-AifNCSpPNTa3h" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/3G1bWX8lo0k?si=6HeTsZyLUyBklNm0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/WHYUyxxhGSk?si=i72YLPYcr4S8f3s-" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
            } elseif ($user_level == 'A2') {
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/Gn1tlmZGK_M?si=HOT334F6v9g0AgKZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/M-C0ugd52p4?si=2kXMNUgt94ye9HMY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/ELvamOwhB1E?si=RHUESDV_rWyGJ4Mg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/-nVvGQYDwPM?si=xvNtFrp8_fA3gBbs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/qtTVDjVuf6I?si=421Ws9a5zZU-SESd" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/tm6q_GfQuqA?si=IK7LzHRFMIgSyCZD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/y0CFWCoxY_U?si=twnNSo1A62GyJVyT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/yOTb8_IY1lU?si=Dkjc-VmnSsQxWwMA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/YbAY-x9vsNQ?si=Mrs--IVXDo1l-7aT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
            } elseif ($user_level == 'B1') {
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/GwVYcIQRY2I?si=l8S0wbqq94f4yfwC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/iFNFD0pS1gk?si=FCtM3SAWZ_OcWGuc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/ZASew_5jFiw?si=6ziXPkRnWBwijPxZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/XUuJy2zzteU?si=8HQcYctQM7M_LEPN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/rcfLoIyjBkU?si=O1EFi-nZdwhCU4pL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/LgDyfFsGRLw?si=oUfSVCNR_axyQ1kP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/XGbecw05t2o?si=FyGv8qZs-dxz-yDz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/x-URmFJPCi8?si=PzdgiAiklrmwD6yT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/J3XiwP0mEjQ?si=qBwA6Nw2Wtu835bx" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
            } elseif ($user_level == 'B2') {
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/OUX-kKRR3qk?si=apSqcgp7QRpvEXkq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/J3HEXNGNt_g?si=3B6mVG0I8215AcFP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/eFmfoeTkhH0?si=6NbjNPtosNoTXGF5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/suvWfcn_qvY?si=6gfmADMo4_u6rFM6" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/k99hiRl-yxs?si=iiktZccAMnfm9U0X" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/eRyipCWSpgA?si=4s6DW8jrgZ8NtUyb" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/65VSKhdUorM?si=obbvraOXdAGxrcGb" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/8G2kKRqsMuQ?si=7T_ZOe38Pcj-WQdF" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/SC143rENuqQ?si=RlHvkXCI0YRPNG3D" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
            }
        } else {

            echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/xhDLXFJNwBY?si=xjG4aBzBaFqceP42" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/gMHxEO3LrQg?si=-uXTFP_NDoMGemF_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/6fmSFanrHN4?si=U512k4JeGNe825uq" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/PWxci3bYpek?si=IhTjGsfHida8CMXM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/szK6cb-xiu4?si=igP31HvSq-hPft8b" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/rglxaZ2-4i4?si=3PBiT3Q-LlC3gWrj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/gAHiiica4cQ?si=zSdmAP31vku8K9pL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/wND26Pwl-rw?si=eBmMuxCUzJfowQfi" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/-qj_nSr7X2I?si=EtHtQ-cnfXHfrX13" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/Gn1tlmZGK_M?si=HOT334F6v9g0AgKZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/M-C0ugd52p4?si=2kXMNUgt94ye9HMY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/ELvamOwhB1E?si=RHUESDV_rWyGJ4Mg" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/-nVvGQYDwPM?si=xvNtFrp8_fA3gBbs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/qtTVDjVuf6I?si=421Ws9a5zZU-SESd" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/tm6q_GfQuqA?si=IK7LzHRFMIgSyCZD" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/y0CFWCoxY_U?si=twnNSo1A62GyJVyT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/yOTb8_IY1lU?si=Dkjc-VmnSsQxWwMA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/YbAY-x9vsNQ?si=Mrs--IVXDo1l-7aT" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/GwVYcIQRY2I?si=l8S0wbqq94f4yfwC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/iFNFD0pS1gk?si=FCtM3SAWZ_OcWGuc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/ZASew_5jFiw?si=6ziXPkRnWBwijPxZ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/XUuJy2zzteU?si=8HQcYctQM7M_LEPN" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/rcfLoIyjBkU?si=O1EFi-nZdwhCU4pL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/LgDyfFsGRLw?si=oUfSVCNR_axyQ1kP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/XGbecw05t2o?si=FyGv8qZs-dxz-yDz" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/J3HEXNGNt_g?si=3B6mVG0I8215AcFP" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                echo '<iframe width="560" height="315" src="https://www.youtube.com/embed/eFmfoeTkhH0?si=6NbjNPtosNoTXGF5" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>';
                                       
        }
        ?>

    </article>
   
</body>

</html>